### ISSUE TITLE
Callback was already called.

### ISSUE THREAD

**Issue by gajus** [zoobestik/csso-webpack-plugin#16]
It appears that `csso-webpack-plugin` has some sort of concurrency condition:

```
/dev/node_modules/async/dist/async.js:955
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /dev/node_modules/async/dist/async.js:955:32
    at /dev/node_modules/csso-webpack-plugin/lib/index.js:185:32
    at /dev/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/dev/node_modules/async/dist/async.js:1055:9)
    at eachOf (/dev/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/dev/node_modules/async/dist/async.js:3158:5)
    at /dev/node_modules/csso-webpack-plugin/lib/index.js:118:37
    at /dev/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/dev/node_modules/async/dist/async.js:1055:9)
    at eachOf (/dev/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/dev/node_modules/async/dist/async.js:3158:5)
    at Compilation.<anonymous> (/dev/node_modules/csso-webpack-plugin/lib/index.js:117:33)
    at next (/dev/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.<anonymous> (/dev/node_modules/babel-minify-webpack-plugin/dist/index.js:102:7)
    at next (/dev/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/dev/node_modules/babel-webpack-plugin/index.js:93:5)
    at Compilation.applyPluginsAsyncSeries (/dev/node_modules/tapable/lib/Tapable.js:206:13)
    at applyPluginsAsync.err (/dev/node_modules/webpack/lib/Compilation.js:663:10)
    at next (/dev/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/dev/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)
    at Compilation.applyPluginsAsyncSeries (/dev/node_modules/tapable/lib/Tapable.js:206:13)
    at applyPluginsAsyncSeries (/dev/node_modules/webpack/lib/Compilation.js:659:9)
    at next (/dev/node_modules/tapable/lib/Tapable.js:202:11)
    at /dev/node_modules/extract-text-webpack-plugin/dist/index.js:244:13
    at /dev/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/dev/node_modules/async/dist/async.js:1050:13)
    at /dev/node_modules/async/dist/async.js:958:16
    at /dev/node_modules/extract-text-webpack-plugin/dist/index.js:227:15
    at /dev/node_modules/async/dist/async.js:473:16
    at eachOfArrayLike (/dev/node_modules/async/dist/async.js:1043:9)

```

It is a large project. I get this inconsistently. No clue what could trigger it.

The only configuration I have is:

```js
new CssoWebpackPlugin({
    beforeCompress (ast, options) {
      options.usage = {
        scopes: getScopes(ast)
      };
    }
  })

```

### Specifications
- **CSSO Plugin version**: v1.0.0-beta.12
- **Webpack version**: v3.11.0
- **CSSO version**: v3.5.0
- **Node + npm versions**: v9.8.0 and v5.6.0

**/cc** @zoobestik

**Comment by gajus** [comment]
I figured as much as that the callback _is_ called multiple times.

The subject file to blame is manifest file, which is a file created using https://www.npmjs.com/package/webpack-assets-manifest.

**Comment by gajus** [comment]
The issue arrises when the callback throws an error,

https://github.com/zoobestik/csso-webpack-plugin/blob/9cf1e223e1213fbf2ffcf96ccd8a698fcf06fb23/src/index.js#L79

In that case, the async is not completed and you arrive at:

https://github.com/zoobestik/csso-webpack-plugin/blob/9cf1e223e1213fbf2ffcf96ccd8a698fcf06fb23/src/index.js#L144

The actual error is:

> Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.

I have not figured out whether this is directly related to `csso-webpack-plugin`.

**Comment by gajus** [comment]
It looks like error is only triggered when I add `babel-minify-webpack-plugin` plugin. Somehow the latter messes up sourcemap mapping.

Here is a relevant issue.

https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68

Seems that `csso-webpack-plugin` is not to blame here.

However, `csso-webpack-plugin` logic needs to be fixed to prevent the callback being called twice. Otherwise the underlying error is masked.

**Comment by zoobestik** [comment]
`async` dropped from **v2.0.0**, let me know, if you will help problems with new versions.
